#!/usr/bin/env bash
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$PROJECT_DIR"

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || { echo "❌ Missing required command: $1"; exit 1; }
}

prompt() {
  local var_name="$1"; shift
  local label="$1"; shift
  local default_value="${1:-}"
  local secret="${2:-false}"

  local value
  if [[ "$secret" == "true" ]]; then
    read -r -s -p "$label [$default_value]: " value
    echo
  else
    read -r -p "$label [$default_value]: " value
  fi

  value="${value:-$default_value}"
  printf -v "$var_name" '%s' "$value"
}

rand_hex() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 16
  else
    date +%s | sha256sum | cut -c1-32
  fi
}

echo "🚀 OpenClaw-3CX Interactive Setup"
echo "This wizard writes .env + voice-app/config/devices.json"
echo

need_cmd docker
need_cmd jq

ARCH="$(uname -m)"
DEFAULT_IP="$(hostname -I 2>/dev/null | awk '{print $1}')"
DEFAULT_IP="${DEFAULT_IP:-127.0.0.1}"
DEFAULT_SECRET="$(rand_hex)"

prompt EXTERNAL_IP "Server IP (LAN/Tailscale)" "$DEFAULT_IP"
prompt SIP_DOMAIN "3CX domain (e.g. company.3cx.cloud)" "1664.3cx.cloud"
prompt SIP_REGISTRAR "SIP registrar (usually 127.0.0.1 with local SBC)" "127.0.0.1"
prompt SIP_TRUNK_HOST "SIP trunk host for outbound (usually server IP)" "$EXTERNAL_IP"
prompt OPENCLAW_HOST "OpenClaw host" "127.0.0.1"
prompt OPENCLAW_PORT "OpenClaw port" "18790"
prompt CLAUDE_API_URL "Voice->Bridge URL" "http://127.0.0.1:3333"
prompt DRACHTIO_SECRET "Drachtio secret" "$DEFAULT_SECRET"

echo
echo "📞 Default calling device"
prompt DEVICE_NAME "Device name" "Luky"
prompt SIP_EXTENSION "Extension number" "12611"
prompt SIP_AUTH_ID "SIP Auth ID (from 3CX IP Phone tab)" "$SIP_EXTENSION"
prompt SIP_PASSWORD "SIP Password (from 3CX IP Phone tab)" "" true
prompt DEVICE_LANGUAGE "Device language (he/en/etc)" "he"
prompt DEVICE_GREETING "Greeting text" "שלום! אני לוקי, העוזר שלך. במה אוכל לעזור?"
prompt DEVICE_THINKING "Thinking phrase" "רגע אחד..."
prompt DEVICE_PROMPT "System prompt" "You are Luky, a helpful AI assistant. Always respond in Hebrew. Keep responses under 40 words."

cat > .env <<ENV
# Generated by setup-interactive.sh on $(date -u +'%Y-%m-%d %H:%M:%S UTC')
EXTERNAL_IP=$EXTERNAL_IP

DRACHTIO_HOST=127.0.0.1
DRACHTIO_PORT=9022
DRACHTIO_SECRET=$DRACHTIO_SECRET
DRACHTIO_SIP_PORT=5070

FREESWITCH_HOST=127.0.0.1
FREESWITCH_PORT=8021
FREESWITCH_SECRET=JambonzR0ck$

SIP_DOMAIN=$SIP_DOMAIN
SIP_REGISTRAR=$SIP_REGISTRAR
SIP_EXTENSION=$SIP_EXTENSION
SIP_AUTH_ID=$SIP_AUTH_ID
SIP_PASSWORD=$SIP_PASSWORD
DEFAULT_CALLER_ID=+$SIP_EXTENSION

CLAUDE_API_URL=$CLAUDE_API_URL

HTTP_PORT=3000
WS_PORT=3001
AUDIO_DIR=/app/audio

MAX_CONVERSATION_TURNS=10
OUTBOUND_RING_TIMEOUT=30
SIP_TRUNK_HOST=$SIP_TRUNK_HOST
SIP_AUTH_USERNAME=$SIP_AUTH_ID
SIP_AUTH_PASSWORD=$SIP_PASSWORD

OPENCLAW_HOST=$OPENCLAW_HOST
OPENCLAW_PORT=$OPENCLAW_PORT
ENV

mkdir -p voice-app/config
jq -n \
  --arg ext "$SIP_EXTENSION" \
  --arg name "$DEVICE_NAME" \
  --arg auth "$SIP_AUTH_ID" \
  --arg pass "$SIP_PASSWORD" \
  --arg lang "$DEVICE_LANGUAGE" \
  --arg greeting "$DEVICE_GREETING" \
  --arg thinking "$DEVICE_THINKING" \
  --arg prompt "$DEVICE_PROMPT" \
  '{($ext): {name:$name, extension:$ext, authId:$auth, password:$pass, language:$lang, greeting:$greeting, thinkingPhrase:$thinking, prompt:$prompt}}' \
  > voice-app/config/devices.json

chmod 600 .env voice-app/config/devices.json

echo
read -r -p "📦 Create encrypted-ish local config backup now? (Y/n) " DO_BACKUP
if [[ ! "$DO_BACKUP" =~ ^[Nn]$ ]]; then
  ./scripts/backup-config.sh
fi

read -r -p "🐳 Start services now? (Y/n) " START_NOW
if [[ ! "$START_NOW" =~ ^[Nn]$ ]]; then
  if [[ "$ARCH" == "aarch64" || "$ARCH" == "arm64" ]]; then
    docker compose -f docker-compose.yml -f docker-compose.arm64.yml up -d
  else
    docker compose up -d
  fi

  echo
  echo "🔍 Health checks"
  curl -sf http://127.0.0.1:3333/health >/dev/null && echo "✅ claude-api-server healthy" || echo "⚠️ claude-api-server not responding"
  curl -sf http://127.0.0.1:3000/health >/dev/null && echo "✅ voice-app healthy" || echo "⚠️ voice-app not responding"
fi

echo
echo "✅ Interactive setup complete"
echo "- .env written"
echo "- voice-app/config/devices.json written"
echo "- Run backup any time: ./scripts/backup-config.sh"
