#!/usr/bin/env bash
set -euo pipefail

SKILL_DIR="${HOME}/.claude/skills/Call"
mkdir -p "$SKILL_DIR/bin" "$SKILL_DIR/lib" "$SKILL_DIR/workflows"

DEFAULT_API="http://127.0.0.1:3000"
DEFAULT_EXT="12610"
DEFAULT_CALLER="12611"
DEFAULT_DEVICE="VoiceBot"
DEFAULT_MODE="conversation"

read -rp "Voice API base URL [$DEFAULT_API]: " API_BASE_URL
API_BASE_URL="${API_BASE_URL:-$DEFAULT_API}"

read -rp "Your extension (target for me/myself) [$DEFAULT_EXT]: " USER_EXT
USER_EXT="${USER_EXT:-$DEFAULT_EXT}"

read -rp "Default caller ID (your AI extension) [$DEFAULT_CALLER]: " DEFAULT_CALLER_ID
DEFAULT_CALLER_ID="${DEFAULT_CALLER_ID:-$DEFAULT_CALLER}"

read -rp "Default device name [$DEFAULT_DEVICE]: " DEVICE_NAME
DEVICE_NAME="${DEVICE_NAME:-$DEFAULT_DEVICE}"

read -rp "Default call mode (announce|conversation) [$DEFAULT_MODE]: " DEFAULT_CALL_MODE
DEFAULT_CALL_MODE="${DEFAULT_CALL_MODE:-$DEFAULT_MODE}"

cat > "$SKILL_DIR/lib/api.py" <<PY
"""
Voice API Client
Auto-generated by install-skill-interactive.sh
"""
import json
import urllib.request
import urllib.error
from typing import Optional, Dict, Any

API_BASE_URL = "${API_BASE_URL}"
DEFAULT_CALLER_ID = "${DEFAULT_CALLER_ID}"
DEFAULT_CALL_MODE = "${DEFAULT_CALL_MODE}"
TIMEOUT_SECONDS = 30

CONTACTS = {
    "me": "${USER_EXT}",
    "myself": "${USER_EXT}",
}

DEVICES = {
    "${DEVICE_NAME,,}": {
        "name": "${DEVICE_NAME}",
        "extension": "${DEFAULT_CALLER_ID}",
        "description": "Default AI device"
    }
}

DEFAULT_DEVICE = "${DEVICE_NAME}"

class VoiceAPIError(Exception):
    pass


def resolve_contact(target: str) -> str:
    t = (target or "").strip().lower()
    return CONTACTS.get(t, target)


def initiate_call(to: str, message: str, mode: str = DEFAULT_CALL_MODE, device: Optional[str] = None) -> Dict[str, Any]:
    payload = {
        "to": resolve_contact(to),
        "message": message,
        "mode": mode,
    }
    if device:
        payload["device"] = device
    data = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(
        API_BASE_URL + "/api/outbound-call",
        data=data,
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    with urllib.request.urlopen(req, timeout=TIMEOUT_SECONDS) as resp:
        return json.loads(resp.read().decode("utf-8"))
PY

cat > "$SKILL_DIR/bin/call" <<PY
#!/usr/bin/env python3
import argparse
from lib.api import initiate_call

p = argparse.ArgumentParser()
p.add_argument("cmd", choices=["outbound"]) 
p.add_argument("to")
p.add_argument("--message", required=True)
p.add_argument("--mode", default=None)
p.add_argument("--device", default=None)
args = p.parse_args()

mode = args.mode if args.mode else None
res = initiate_call(args.to, args.message, mode=mode or "conversation", device=args.device)
print(res)
PY
chmod +x "$SKILL_DIR/bin/call"

cat > "$SKILL_DIR/SKILL.md" <<MD
---
name: Call
description: Outbound voice calling via SIP from Claude Code.
---

Use:
- call outbound me --message "Backup complete" --mode conversation
MD

cat > "$SKILL_DIR/workflows/MakeCall.md" <<MD
# MakeCall
1) Resolve contact
2) Trigger outbound call via /api/outbound-call
3) Report callId and status
MD

echo "Installed Call skill at: $SKILL_DIR"
echo "Testing API health..."
if curl -fsS "${API_BASE_URL}/health" >/dev/null 2>&1; then
  echo "Voice API health: OK"
else
  echo "Voice API health: unreachable (continuing)"
fi

echo "Done. Try: $SKILL_DIR/bin/call outbound me --message \"בדיקה\" --mode ${DEFAULT_CALL_MODE}"
